@endpoint = https://4g7hct7m1k.execute-api.ap-south-1.amazonaws.com/prod

GET {{endpoint}}/hello/
###

GET {{endpoint}}/spaces?spaceId=21be3f5c-b905-4d1d-90be-2db5a49f995d
###

GET {{endpoint}}/spaces
###

GET {{endpoint}}/spaces?location=Manjari%20Budruk
###

PUT {{endpoint}}/spaces?spaceId=21be3f5c-b905-4d1d-90be-2db5a49f995d
Content-Type: application/json

{
  "location": "Keshavnagar"
}
###

POST {{endpoint}}/spaces/
Content-Type: application/json

{
  "body": "{\"var1\":\"Vish\",\"var2\":\"11\",\"location\":\"Pune\"}",
  "currentTime": "{{$timestamp}}",
  "location": "Pune"
}
###

DELETE {{endpoint}}/spaces?spaceId=e3db9054-8468-4f33-a262-a9b3aa48e7f2
###