@endpoint = https://4g7hct7m1k.execute-api.ap-south-1.amazonaws.com/prod

GET {{endpoint}}/hello/
###

GET {{endpoint}}/spaces?spaceId=e3db9054-8468-4f33-a262-a9b3aa48e7f2
###

POST {{endpoint}}/spaces/
Content-Type: application/json

{
  "body": "{\"var1\":\"Ninja Hattori\",\"var2\":\"11\",\"var3\":\"Ning Ning\"}",
  "currentTime": "{{$timestamp}}"
}
###